# creating arrays

In [1]:
import numpy as np

In [4]:
my_list1 = [1,2,3,4]

In [5]:
my_array1 = np.array(my_list1)

In [6]:
my_array1

array([1, 2, 3, 4])

In [7]:
my_list2 = [11,22,33,44]

In [8]:
my_lists = [my_list1,my_list2]

In [13]:
my_array_2 = np.array(my_lists)

In [14]:
my_array_2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [16]:
my_array_2.shape

(2, 4)

In [17]:
my_array_2.dtype

dtype('int32')

In [19]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
my_zeros_array = np.zeros(5)

In [21]:
my_zeros_array.dtype

dtype('float64')

In [22]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
np.empty(5)

array([1.11325339e-311, 2.16847421e-028, 1.10743249e-312, 0.00000000e+000,
       0.00000000e+000])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [27]:
np.arange(5,50,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

# using arrays and scalars

In [29]:
from __future__ import division

In [30]:
5/2

2.5

In [33]:
arr1 = np.array([[1,2,3,4],[8,9,10,11]])

In [34]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [35]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [36]:
arr1 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [37]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [38]:
arr1 **3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [42]:
0|0

0

# Indexing arrays

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [15]:

arr[:-1]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr[0:5] = 100

In [17]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [18]:
arr = np.arange(0,11)

In [19]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
slice_of_arr = arr[0:6]

In [21]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [22]:
slice_of_arr[:] = 99

In [23]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [24]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

as we have taken a slice of array and tried to make changes on it. so, changes effect the slice as well as original array.

to avoid that you need make a copy of array first.

In [25]:
arr_copy = arr.copy()

In [26]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy[:3]=11

In [28]:
arr_copy

array([11, 11, 11, 99, 99, 99,  6,  7,  8,  9, 10])

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[1]

array([20, 25, 30])

In [33]:
arr_2d[0]

array([ 5, 10, 15])

In [34]:
arr_2d[1][0]

20

In [35]:
arr_2d[2][2]

45

In [43]:
#arr_2d[start k do,one se onward]


arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [44]:
arr_2d[2]

array([35, 40, 45])

In [45]:
arr2d = np.zeros((10,10))

In [46]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [54]:
arr_length = arr2d.shape[1]

In [55]:
arr_length

10

In [56]:
for i in range(arr_length):
    arr2d[i]=1

In [57]:
arr2d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [58]:
for i in range(arr_length):
    arr2d[i]=i

In [59]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [62]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [63]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

# array transposition

In [64]:
arr = np.arange(50).reshape((10,5))

In [65]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [66]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [67]:
#dot product between transpose and original array
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [68]:
#arr3d = np.arange(50).reshape(five items,five rows,two columns)

arr3d = np.arange(50).reshape(5,5,2)

In [69]:
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [112]:
arr3d.transpose((1,0,2))

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [85]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [92]:
arr.swapaxes(0,1)

array([[1],
       [2],
       [3]])

# Universal array function

In [114]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [116]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [117]:
A = np.random.randn(10)
A

array([-0.5668106 ,  0.87769743, -0.88111229,  1.01139823,  1.07724601,
       -0.30535654, -1.56460424, -0.51333692, -0.41399009,  0.66240681])

In [120]:
B = np.random.randn(10)
B

array([-0.33797483,  0.39589917,  0.21319283,  0.50042461,  0.91825463,
       -1.5767688 , -1.13971813, -0.21546286,  0.11474592,  0.4218752 ])

In [121]:
#binary functions

np.add(A,B)



array([-0.90478542,  1.2735966 , -0.66791946,  1.51182285,  1.99550063,
       -1.88212534, -2.70432237, -0.72879978, -0.29924417,  1.08428201])

In [123]:
np.maximum(A,B)

array([-0.33797483,  0.87769743,  0.21319283,  1.01139823,  1.07724601,
       -0.30535654, -1.13971813, -0.21546286,  0.11474592,  0.66240681])

In [124]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

# Array processing